apiVersion: apps/v1
kind: Deployment
metadata:
  name: active-mq
  namespace: finance-db
spec:
  selector:
    matchLabels:
      app: active-mq
  template:
    metadata:
      labels:
        app: active-mq
    spec:
      containers:
      - name: active-mq
        image: activemq:1.0.0
        resources:
         requests:
            memory: 500Mi
            cpu: 200m        
         limits:
            memory: "500Mi"
            cpu: "200m"
        volumeMounts:
        - name: active-creds
          mountPath: /home/alpine/apache-activemq-5.15.10/conf/jetty-realm.properties
          subPath: jetty-realm.properties
      volumes:
       - name: active-creds
         secret:
          secretName: creds
      restartPolicy: Always    
        
